### ISSUE TITLE
dependency on Set

### ISSUE THREAD

**Issue by jihopark** [jaysoo/react-native-activity-android#1]
Hi, I love your library, but can u add `Set` as a dependency? it won't build on Xcode (although this library is an android module my app is for both platform)

I had to put `Set` as my package.json to get it run

**Comment by jaysoo** [comment]
Hi @jihopark, thanks for reporting this issue.

I had assumed Set needed to be required, but it is polyfilled for us by babel via es2015 preset.

I have removed it and tested that it does compile and run on iOS. This is the example I ran: https://github.com/jaysoo/react-native-activity-android/blob/master/Example/index.ios.js.

Update to 0.17.3 and this will be resolved. :)

**Comment by jihopark** [comment]
i updated and it is solved. thanks for your fast response! @jaysoo
