### ISSUE TITLE
Doesnt work on RN 0.29

### ISSUE THREAD

**Issue by pewh** [jaysoo/react-native-activity-android#2]

**Comment by tje3d** [comment]
Any PR or Something ?

**Comment by awesomejerry** [comment]
Try it
https://github.com/jaysoo/react-native-activity-android/pull/3

**Comment by pewh** [comment]
Thanks @awesomejerry. It's work on 0.29. But unfortunately, it didn't work on RN 0.34. I got this error:
![1](https://cloud.githubusercontent.com/assets/881358/19018521/98bf169c-888e-11e6-828c-63f8ced10d52.png)

**Comment by awesomejerry** [comment]
It works on my rn@0.34.0. Have you added multiple ActivityAndroidPackage in your MainApplication.java?
<img width="414" alt="2016-10-02 17 14 30" src="https://cloud.githubusercontent.com/assets/6601073/19019726/bec2136e-88c3-11e6-9e7d-496360c30d5e.png">

or your app/build.gradle
<img width="528" alt="2016-10-02 17 16 14" src="https://cloud.githubusercontent.com/assets/6601073/19019733/f655f048-88c3-11e6-85a5-219155ac7164.png">

or your settings.gradle
<img width="1081" alt="2016-10-02 17 16 40" src="https://cloud.githubusercontent.com/assets/6601073/19019737/0be42a88-88c4-11e6-9950-d58d7e9567bf.png">

**Comment by pewh** [comment]
You right! I have multiple ActivityAndroidPackage inside MainApplication.java.
I don't know why `react-native link` add multiple `new ActivityAndroidPackage()` on MainApplication.java.
Anyway thanks for the help! :beers:
